[package]
name = "rust_tsp"
version = "0.1.0"
authors = ["Bartłomiej Wierciński <bmwbartek1@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.3.1"
rand = "0.8.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lib_benchmark"
harness = false

[features]
html_reports = []
